### ISSUE TITLE
First snapshot fails to update error

### ISSUE THREAD

**Issue by 2hyunbin** [dydxprotocol/grpc-stream-client#14]
Cloning and running the current version of client causes photo-like errors. It occurs in the process of updating the initial snapshot when start the grpc client. I modified the part marked in the second photo to <0 and it works. 

Please check if it needs to be modified

![image](https://github.com/user-attachments/assets/ef74694b-6958-4517-bb46-a5ac31586f18)

![image](https://github.com/user-attachments/assets/ab1a07ca-1b13-4c36-a4ff-ecdefb5f5ac4)

**Comment by matthewdowney** [comment]
Hi, can you try updating the requirements.txt file to set `v4-proto` to match your node (5.2.2 I think)? 

https://pypi.org/project/v4-proto/5.2.2/

The main branch is still using
https://github.com/dydxprotocol/grpc-stream-client/blob/c18b7ae0b1e23a99eed89748ff26ca2274e68289/requirements.txt#L6

Let me know if that fixes it for you.
